=== beazt123/SGMRTNav/docs/station-list-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://yourdomain.com/schemas/station.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": { "type": "string" },
      "id":  {
        "type": "integer",
        "minimum": 1
      },
      "line": { "type": "string" },
      "transitions": {
        "type": "object",
        "patternProperties": {
          "^[A-Z]{2}$": {
            "type": "integer",
            "minimum": 1
          }
        },
        "properties": {
          "exit": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false
      }
    },
    "required": ["name", "id", "line", "transitions"],
    "additionalProperties": false
  }
}

=== beazt123/SGMRTNav/src/main/resources/json-network-data/CEL-station-list.json
[
  {
    "name": "Promenade",
    "id": 0,
    "line": "CE",
    "transitions": {
      "exit": 2,
      "DT": 7,
      "CC": 9
    }
  },
  {
    "name": "Bayfront",
    "id": 1,
    "line": "CE",
    "transitions": {
      "exit": 3,
      "DT": 3
    }
  },{
    "name": "Marina Bay",
    "id": 2,
    "line": "CE",
    "transitions": {
      "exit": 1
    }
  }
]
