=== beazt123/SGMRTNav/docs/station-list-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://yourdomain.com/schemas/station.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": { "type": "string" },
      "id":  {
        "type": "integer",
        "minimum": 1
      },
      "line": { "type": "string" },
      "transitions": {
        "type": "object",
        "patternProperties": {
          "^[A-Z]{2}$": {
            "type": "integer",
            "minimum": 1
          }
        },
        "properties": {
          "exit": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false
      }
    },
    "required": ["name", "id", "line", "transitions"],
    "additionalProperties": false
  }
}

=== beazt123/SGMRTNav/src/main/resources/json-network-data/CG-station-list.json
[
  {
    "name": "Tanah Merah",
    "id": 0,
    "line": "CG",
    "transitions": {
      "exit": 7,
      "EW": 7
    }
  },{
    "name": "Expo",
    "id": 1,
    "line": "CG",
    "transitions": {
      "exit": 5,
      "DT": 13
    }
  },{
    "name": "Changi Airport",
    "id": 2,
    "line": "CG",
    "transitions": {
      "exit": 20
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/SE-station-list.json
[
  {
    "name": "Seng Kang",
    "id": 0,
    "line": "SE",
    "transitions": {
      "exit": 2,
      "NE": 2,
      "SW": 2
    }
  },{
    "name": "Compassvale",
    "id": 1,
    "line": "SE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Rumbia",
    "id": 2,
    "line": "SE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Bakau",
    "id": 3,
    "line": "SE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Kangkar",
    "id": 4,
    "line": "SE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Ranggung",
    "id": 5,
    "line": "SE",
    "transitions": {
      "exit": 2
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/TEL-station-list.json
[
  {
    "name": "Woodlands North",
    "id": 1,
    "line": "TE",
    "transitions": {
      "exit": 1
    }
  },{
    "name": "Woodlands",
    "id": 2,
    "line": "TE",
    "transitions": {
      "exit": 4,
      "NS": 17
    }
  },{
    "name": "Woodlands South",
    "id": 3,
    "line": "TE",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Springleaf",
    "id": 4,
    "line": "TE",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Lentor",
    "id": 5,
    "line": "TE",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Mayflower",
    "id": 6,
    "line": "TE",
    "transitions": {
      "exit": 5
    }
  },{
    "name": "Bright Hill",
    "id": 7,
    "line": "TE",
    "transitions": {
      "exit": 9
    }
  },{
    "name": "Upper Thompson",
    "id": 8,
    "line": "TE",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Caldecott",
    "id": 9,
    "line": "TE",
    "transitions": {
      "exit": 2,
      "CC": 19
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/EWL-station-list.json
[
  {
    "name": "Pasir Ris",
    "id": 1,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Tampines",
    "id": 2,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Simei",
    "id": 3,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Tanah Merah",
    "id": 4,
    "line": "EW",
    "transitions": {
      "exit": 7,
      "CG": 7
    }
  },{
    "name": "Bedok",
    "id": 5,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Kembangan",
    "id": 6,
    "line": "EW",
    "transitions": {
      "exit": 12
    }
  },{
    "name": "Eunos",
    "id": 7,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Paya Lebar",
    "id": 8,
    "line": "EW",
    "transitions": {
      "exit": 13,
      "CC": 1
    }
  },{
    "name": "Aljunied",
    "id": 9,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Kallang",
    "id": 10,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Lavender",
    "id": 11,
    "line": "EW",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Bugis",
    "id": 12,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "City Hall",
    "id": 13,
    "line": "EW",
    "transitions": {
      "exit": 9,
      "NS": 6
    }
  },{
    "name": "Raffles Place",
    "id": 14,
    "line": "EW",
    "transitions": {
      "exit": 10,
      "NS": 5
    }
  },{
    "name": "Tanjong Pagar",
    "id": 15,
    "line": "EW",
    "transitions": {
      "exit": 6
    }
  },{
    "name": "Outram Park",
    "id": 16,
    "line": "EW",
    "transitions": {
      "exit": 8,
      "NE": 12
    }
  },{
    "name": "Tiong Baru",
    "id": 17,
    "line": "EW",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Redhill",
    "id": 18,
    "line": "EW",
    "transitions": {
      "exit": 11
    }
  },{
    "name": "Queenstown",
    "id": 19,
    "line": "EW",
    "transitions": {
      "exit": 11
    }
  },{
    "name": "Commonwealth",
    "id": 20,
    "line": "EW",
    "transitions": {
      "exit": 14
    }
  },{
    "name": "Buona Vista",
    "id": 21,
    "line": "EW",
    "transitions": {
      "exit": 11,
      "CC": 20
    }
  },{
    "name": "Dover",
    "id": 22,
    "line": "EW",
    "transitions": {
      "exit": 9
    }
  },{
    "name": "Clementi",
    "id": 23,
    "line": "EW",
    "transitions": {
      "exit": 14
    }
  },{
    "name": "Jurong East",
    "id": 24,
    "line": "EW",
    "transitions": {
      "exit": 7,
      "NS": 7
    }
  },{
    "name": "Chinese Garden",
    "id": 25,
    "line": "EW",
    "transitions": {
      "exit": 6
    }
  },{
    "name": "Lakeside",
    "id": 26,
    "line": "EW",
    "transitions": {
      "exit": 6
    }
  },{
    "name": "Boon Lay",
    "id": 27,
    "line": "EW",
    "transitions": {
      "exit": 5
    }
  },{
    "name": "Pioneer",
    "id": 28,
    "line": "EW",
    "transitions": {
      "exit": 9
    }
  },{
    "name": "Joo Koon",
    "id": 29,
    "line": "EW",
    "transitions": {
      "exit": 8
    }
  },{
    "name": "Gul Circle",
    "id": 30,
    "line": "EW",
    "transitions": {
      "exit": 13
    }
  },{
    "name": "Tuas Cresent",
    "id": 31,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Tuas West Road",
    "id": 32,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  },{
    "name": "Tuas Link",
    "id": 33,
    "line": "EW",
    "transitions": {
      "exit": 7
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/BP-station-list.json
[
  {
    "name": "Choa Chu Kang",
    "id": 1,
    "line": "BP",
    "transitions": {
      "exit": 2,
      "NS": 2
    }
  },{
    "name": "South View",
    "id": 2,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Keat Hong",
    "id": 3,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Teck Whye",
    "id": 4,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Phoenix",
    "id": 5,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Bukit Panjang",
    "id": 6,
    "line": "BP",
    "transitions": {
      "exit": 2,
      "DT": 2
    }
  },{
    "name": "Petir",
    "id": 7,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Pending",
    "id": 8,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Bangkit",
    "id": 9,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Fajar",
    "id": 10,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Segar",
    "id": 11,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Jelapang",
    "id": 12,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Senja",
    "id": 13,
    "line": "BP",
    "transitions": {
      "exit": 2
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/SW-station-list.json
[
  {
    "name": "Seng Kang",
    "id": 0,
    "line": "SW",
    "transitions": {
      "exit": 2,
      "NE": 2,
      "SE": 2
    }
  },{
    "name": "Cheng Lim",
    "id": 1,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Farmway",
    "id": 2,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Kupang",
    "id": 3,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Thanggam",
    "id": 4,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Fernvale",
    "id": 5,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Layar",
    "id": 6,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Tongkang",
    "id": 7,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Renjong",
    "id": 8,
    "line": "SW",
    "transitions": {
      "exit": 2
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/NEL-station-list.json
[
  {
    "name": "Punggol",
    "id": 17,
    "line": "NE",
    "transitions": {
      "exit": 5,
      "PE": 14,
      "PW": 14
    }
  }, {
    "name": "Seng Kang",
    "id": 16,
    "line": "NE",
    "transitions": {
      "exit": 5,
      "SW": 14,
      "SE": 14
    }
  }, {
    "name": "Buangkok",
    "id": 15,
    "line": "NE",
    "transitions": {
      "exit": 9
    }
  }, {
    "name": "Hougang",
    "id": 14,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Kovan",
    "id": 13,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Serangoon",
    "id": 12,
    "line": "NE",
    "transitions": {
      "exit": 6,
      "CC": 16
    }
  }, {
    "name": "Woodleigh",
    "id": 11,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Potong Pasir",
    "id": 10,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Boon Keng",
    "id": 9,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Farrer Park",
    "id": 8,
    "line": "NE",
    "transitions": {
      "exit": 8
    }
  }, {
    "name": "Little India",
    "id": 7,
    "line": "NE",
    "transitions": {
      "exit": 8,
      "DT": 17
    }
  }, {
    "name": "Dhoby Ghaut",
    "id": 6,
    "line": "NE",
    "transitions": {
      "exit": 9,
      "CC": 9,
      "NS": 9
    }
  }, {
    "name": "Clarke Quay",
    "id": 5,
    "line": "NE",
    "transitions": {
      "exit": 4
    }
  }, {
    "name": "Chinatown",
    "id": 4,
    "line": "NE",
    "transitions": {
      "exit": 2,
      "CC": 1
    }
  }, {
    "name": "Outram Park",
    "id": 3,
    "line": "NE",
    "transitions": {
      "exit": 12,
      "EW": 6
    }
  }, {
    "name": "Harbourfront",
    "id": 1,
    "line": "NE",
    "transitions": {
      "exit": 9,
      "CC": 9
    }
  }
]

=== beazt123/SGMRTNav/src/main/resources/json-network-data/PE-station-list.json
[
  {
    "name": "Punggol",
    "id": 0,
    "line": "PE",
    "transitions": {
      "exit": 2,
      "PW": 2,
      "NE": 2
    }
  },{
    "name": "Cove",
    "id": 1,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Meridian",
    "id": 2,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Coral Edge",
    "id": 3,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Riviera",
    "id": 4,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Kadaloor",
    "id": 5,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Oasis",
    "id": 6,
    "line": "PE",
    "transitions": {
      "exit": 2
    }
  },{
    "name": "Damai",
    "id": 7,
    "line": "PE",
    "transitions": {
      "exit": 2 
    }
  }
]
